# TODO: trigger only if testing or any other checks previously succeeded
name: Push to DockerHub (pre-release)
on:
  push:
    tags:
      # pre-release tags, examples:
      # v1.0.0-alpha
      # v1.0.0-alpha.1
      # v1.0.0-alpha.beta
      # v1.0.0-beta
      # v1.0.0-beta.2
      # v1.0.0-beta.11
      # v1.0.0-rc.1
      - "v[0-9]+.[0-9]+.[0-9]+-.+"

permissions:
  contents: read
  id-token: write

jobs:
  build-multiarch:
    runs-on: ubuntu-latest-8-cores

    steps:
      - id: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: "false"
      - id: push-beyla-to-dockerhub
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@776d57f0c1cf5bab2fff564229d23efa4a9b7649 # main
        with:
          repository: grafana/beyla
          context: .
          platforms: |-
            "linux/amd64"
            "linux/arm64"
          tags: |-
            "type=semver,pattern={{version}}"
          push: true

      - id: push-beyla-k8s-cache-to-dockerhub
        uses: grafana/shared-workflows/actions/build-push-to-dockerhub@776d57f0c1cf5bab2fff564229d23efa4a9b7649 # main
        with:
          repository: grafana/beyla-k8s-cache
          file: k8scache.Dockerfile
          context: .
          platforms: |-
            "linux/amd64"
            "linux/arm64"
          tags: |-
            "type=semver,pattern={{version}}"
          push: true
