name: Pull request integration tests on VM 6.10 x86_64

on:
  push:
    branches: [ 'main', 'release-*' ]
    paths: [ 'bpf/**' ]
  pull_request:
    branches: [ 'main', 'release-*' ]
    paths: [ 'bpf/**' ]

# Set restrictive permissions at workflow level
permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/workflow_integration_tests_vm.yml
    with:
      arch: x86_64
      kernel-version: 6.10.6
