name: Release binaries
on:
  workflow_call:
    inputs:
      arch:
        description: 'Target architecture to build the binaries'
        required: true
        type: string
      runner:
        description: 'The github runner to run on'
        required: true
        type: string
permissions:
  contents: read
jobs:
  release-binaries:
    name: Release compiled binaries for Linux/${{inputs.arch}}
    runs-on: ${{inputs.runner}}
    strategy:
      matrix:
        go: [ '1.25' ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3.6.1
        with:
          cache: false  # Disable caching to avoid extraction conflicts
          go-version: ${{ matrix.go }}
      - name: Build Go release for linux/${{inputs.arch}}
        run: make artifact
        env:
          GOOS: linux
          GOARCH: ${{ inputs.arch }}
      - name: Upload release asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/beyla.tar.gz
          asset_name: beyla-linux-${{ inputs.arch }}-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
